# Base image
FROM node:18

# Create working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json .
RUN npm install

# Copy the rest of the application
COPY . .

# Expose the service port
EXPOSE 5000

# Start the application
CMD ["npm","run" ,"dev"]
